### ISSUE TITLE
Feature suggestion for decrypt_cookies: extract to reqwest cookie jar

### ISSUE THREAD

**Issue by emarsden** [saying121/tidy-browser#1]
For the decrypt_cookies crate, it would be useful to be able to supply the cookies available as a cookie_jar for the reqwest crate, making it easy to make HTTP reqwests using auth data from a browser. For example using the API in the (unmaintained) bench_scraper crate. 

   https://github.com/goakley/bench_scraper

**Comment by saying121** [comment]
I may need a few weeks before I can come back to discuss how to implement this feature. I'm currently occupied with some matters at company.
